### PR TITLE
Added Search to CreativeTabs

### PR DESCRIPTION
**Pull request by yesimwearingpants**

### CODE REVIEW

**Comment by Drullkus** [comment]
Holy crap, yesterday I was thinking of asking @Vazkii yesterday about a search bar in the creative tab and then re-merge all chisel creative tabs.

**Comment by yesimwearingpants** [comment]
Well this doesn't have Inventory sorting like Botania, But I think that would be ridiculous to do in Chisel

**Comment by yesimwearingpants** [comment]
This works, but I forgot to import SideOnly. I know It works though because I did it on my own mod.

**Comment by Drullkus** [comment]
Wait. Let me ask again

Is this to search for items in the creative tab? Say I pull up the chisel creative tab and type 'Malfunction'. Should it give me "Malfunctioning Fan" and "Transparent Malfunctioning Fan"?

**Comment by yesimwearingpants** [comment]
yes

**Comment by Drullkus** [comment]
Ok that's what I was talking about :P

**Comment by CptSpaceToaster** [comment]
The build isn't happy: http://coloredlightscore.us.to:8080/job/Chisel-2%20v1.7.10-Dev/66/console

Please verify your pull requests compile correctly before submitting them to us.

**Comment by tterrag1098** [comment]
@CptSpaceToaster sorry, but no. it's on us to test PRs, we can't blame him for our lack of testing.

**Comment by CptSpaceToaster** [comment]
@tterrag1098 I agree, it's on us.  I do not intend to force all devs to build the projects before they submit PR's... I hope to get Jenkins doing that.  

I'll edit my language, but this was a suggestion to just "get this working".  As I doubt yesimwearingpants is aware that he broke the build.  Is it his job to know?  No... not that's our job before we blindly accept PRs.  But, if he wants to make additional PR's, then it would be a good check for him to build before sending them to us, so we don't have to outright deny them later.

**Comment by yesimwearingpants** [comment]
I submitted a new PR That Does Build

**Comment by tterrag1098** [comment]
I've already fixed it now

**Comment by yesimwearingpants** [comment]
I don't Consider Undo ing it Fixed ( as I stated earlier "I forgot to import SideOnly" and Side stat was all that was wrong). Sorry If Im sounding Rude, not the intent.

**Comment by TheCricket** [comment]
Wait, did you not code this in a IDE? Because it would have thrown that it wasn't imported

**Comment by tterrag1098** [comment]
?? I didn't undo it. I just added the import you were missing.

**Comment by yesimwearingpants** [comment]
No. gradle eclipe didnt work So I used a Text Editor.
I got it sorted an even Build testedto make sure in this https://github.com/TheCricket/Chisel-2/pull/247 Pr Though

**Comment by yesimwearingpants** [comment]
Oops my bad I went to check how you fixed it and looked at the wmaster branch

**Pull request merged**
