### PR TITLE
Asthetical is not a word

### PR DESCRIPTION
**Pull request by shadowfacts**
According to the Oxford Dictionary

### CODE REVIEW

**Comment by TehNut** [comment]
Nope it's a word. Can confirm.

**Comment by shadowfacts** [comment]
http://www.oxforddictionaries.com/us/spellcheck/all/?q=asthetical

**Comment by TehNut** [comment]
Can confirm: Is real - http://tehnut.info/dictionary.html

**Comment by shadowfacts** [comment]
:laughing: Did you really just add that to your website? :clap:

**Comment by TheCricket** [comment]
Thats what happens when I am tired

**Pull request merged**
