### PR TITLE
Update ru_RU.lang

### PR DESCRIPTION
**Pull request by Adaptivity**
"tile.colored_sand.name=Colored Sand" this change correct, I guess? Also, "Chinese Glass Pane with Golden Grame" shouldn't this be "Chinese Glass Pane with Golden Frame"?

### CODE REVIEW

**Comment by Adaptivity** [comment]
What about "Chinese Glass Pane with Golden Grame"?

**Comment by warlordjones** [comment]
Evidently someone can't spell, you are correct, should be frame, I'll change that in the en_US

**Comment by Adaptivity** [comment]
Also, I made a misspell: "Futuristic Armor Plating with Shining Metal Vits" correct it to "Bits" :smile:

**Comment by TheCricket** [comment]
@warlordjones You do not have permission to accept pull requests.

**Comment by warlordjones** [comment]
Um, ok...

**Comment by warlordjones** [comment]
May I ask why @TheCricket

**Comment by TheCricket** [comment]
There's few mistakes, and remember you are a contributor I gave you access to commit so I didnt havre to accept PR's everyday some things can go through that I find incorrect.

**Comment by warlordjones** [comment]
Sorry, I can't read russian! In future I will leave PRs to you, but I thought it was more like a team with you as the leader than us being contributors and you being the only real 'coder'

**Pull request merged**
