### PR TITLE
Allow some blocks to be colored via the forge recolourBlock method

### PR DESCRIPTION
**Pull request by BigXplosion**
Title says it all...

### CODE REVIEW

**Comment by tterrag1098** [comment]
Could we have some screenshots of what this accomplishes?

**Comment by TheCricket** [comment]
Was just gonna ask the same thing lol

**Comment by BigXplosion** [comment]
well screenshots wouldn't show anything new as the blocks will still show up as they are now. The only thing this PR does is allow these 2 block (Hex and Anti) to be recolored to another color but the same block type using a tool that checks for the recolourBlock Method. Example: I use a Blue IC2 brush on a white hex block => the White Hex block becomes a blue hex block and the tool takes damage. This would work with every tool that checks [this] (https://github.com/BCA-Team/Buildcraft-Additions/blob/multiblockRefinery/src/main/java/buildcraftAdditions/items/Tools/ItemPipeColoringTool.java#L63).

**Comment by TheCricket** [comment]
Ah so you could paint it any hex color

**Comment by BigXplosion** [comment]
yes, that's right!

**Pull request merged**
